# Estatística Descritiva
 
Objetivos: descobrir a quantidade de palavras, sentenças, adjetivos e advérbios nos relatórios nos períodos `t-1`, `t`  e `t+2`.

# Carregar as bibliotecas e o dataset

In [ ]:
import re
import pandas as pd
from unidecode import unidecode
df = pd.read_excel("D:/TCC/Codigos_e_Dastasets/Classes Gramaticais/Dataset_Original/Relatorio_Planilha_Analise_Sentimento1.xlsx")

In [2]:
print(df.head(3))

   Id_Empresa       Nome                                                t-1  \
0           1  Petrobras  A Petróleo Brasileiro S.A.  Petrobras dedicase...
1           2      Ambev  A Companhia de Bebidas das Américas – Ambev (r...
2           3    Via S.A  \n\nA Via Varejo S.A., diretamente ou por meio...

                                                   t  \
0  A Petróleo Brasileiro S.A. - Petrobras dedica-...
1  \nA Ambev S.A. (referida como “Companhia” ou “...
2  \n\nA Via Varejo S.A., diretamente ou por meio...

                                                 t+2
0  A Petróleo Brasileiro S.A. – Petrobras, Socied...
1  A Ambev S.A. (referida como “Companhia”, “Ambe...
2  A Via S.A., diretamente ou por meio de suas co...

# Análise de palavras e sentenças com NLTK

**O que acontece aqui:**
- instala o tokenizador punkt do NLTK
- importa funções de tokenização
- define uma função chamada contar_palavras_sentencas_nltk


**Como a função funciona:**
Para cada texto:
- se o valor estiver vazio ou ausente, ela retorna (0, 0)
- caso contrário:
  - usa sent_tokenize(...) para dividir em sentenças
  - usa word_tokenize(...) para dividir em palavras
  
Depois, ela retorna:
- quantidade de palavras
- quantidade de sentenças

In [10]:
import nltk
nltk.download('punkt')

import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

def contar_palavras_sentencas_nltk(df, coluna_texto="texto"):
    """
    Conta número de palavras e número de sentenças usando NLTK.
    Retorna o DataFrame original com duas novas colunas:
    - n_palavras_nltk
    - n_sentencas_nltk
    """
    
    def processar(texto):
        if pd.isna(texto):
            return 0, 0
        
        # Sentenças
        sentencas = sent_tokenize(texto, language="portuguese")
        
        # Palavras
        palavras = word_tokenize(texto, language="portuguese")
        
        return len(palavras), len(sentencas)
    
    df[f"{coluna_texto}_n_palavras_nltk"], df[f"{coluna_texto}_n_sentencas_nltk"] = zip(*df[coluna_texto].apply(processar))
    return df

df_nltk = df.copy()
df_nltk = contar_palavras_sentencas_nltk(df_nltk, coluna_texto="t-1")
df_nltk = contar_palavras_sentencas_nltk(df_nltk, coluna_texto="t")
df_nltk = contar_palavras_sentencas_nltk(df_nltk, coluna_texto="t+2")

df_nltk = df_nltk.drop(columns=['Nome','t-1','t','t+2'])
df_nltk

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,Id_Empresa,t-1_n_palavras_nltk,t-1_n_sentencas_nltk,t_n_palavras_nltk,t_n_sentencas_nltk,t+2_n_palavras_nltk,t+2_n_sentencas_nltk
0,1,5336,154,5203,123,5226,144
1,2,5455,175,5492,157,5489,177
2,3,5564,153,5459,139,5379,172
3,4,5546,139,5390,141,5458,148
4,5,5445,149,5569,155,5576,141
5,6,5454,169,5486,174,5546,175
6,8,5470,143,5510,138,5323,146
7,9,5473,160,5318,159,5345,166
8,10,5459,149,5445,150,5585,163
9,11,5308,166,5316,164,5308,163
10,12,5506,164,5507,150,5619,166
11,13,5369,167,5374,168,5320,163
12,14,5246,123,5541,128,5539,145
13,15,5310,177,5264,180,5263,179
14,16,5532,130,5475,135,5349,145
15,17,5463,150,5330,117,5527,124
16,18,6079,107,5812,128,5942,105
17,19,5474,154,5542,184,5513,188
18,20,5523,152,5507,159,5525,152
19,21,5705,157,5863,169,5591,154
20,22,5515,179,5444,157,5551,163
21,23,5438,175,5470,182,5577,159
22,24,5430,157,5450,153,5457,164
23,25,5735,174,5780,155,5677,156
24,26,5445,139,5459,141,5520,141
25,27,5656,123,5638,128,6059,130
26,28,5311,142,5441,131,5726,103
27,29,5583,147,5561,142,5708,126
28,30,5651,154,5540,144,5527,142
29,31,5374,167,5389,161,5374,138
30,32,5708,158,5523,142,5704,141
31,33,5266,163,5371,147,5646,153
32,34,5360,151,5360,152,5427,150
33,35,5436,145,5467,153,5624,140
34,36,5413,150,5436,152,5474,140
35,37,5481,157,5458,157,5478,150
36,38,5436,154,5490,157,5476,153
37,39,5469,171,5515,166,5447,169
38,40,5560,156,5594,159,5848,155
39,41,5433,154,5451,148,5391,145
40,42,5396,173,5411,173,5468,162
41,43,5396,148,5684,170,5452,133
42,44,5488,154,5337,154,5346,159
43,45,5330,145,5467,126,5332,137
44,46,5506,143,5515,150,5519,143
45,47,5977,91,6010,89,5608,114
46,48,5426,163,5424,158,5418,165
47,49,5403,176,5345,160,0,0
48,50,5418,137,5491,126,5460,130
49,51,5477,145,5684,116,5481,129

#  Análise de palavras e sentenças com spaCy
Este bloco faz praticamente a mesma coisa do bloco anterior, mas usando spaCy em vez de NLTK.

**O que muda:**
- importa spacy
- carrega o modelo pt_core_news_lg
- define uma função contar_palavras_sentencas_spacy

**Como a função funciona:**
Para cada texto:
- se estiver ausente, retorna zero para palavras e sentenças
- caso contrário:
    - cria um objeto Doc com nlp(texto)
    - conta todos os tokens com len(list(doc))
    - conta as sentenças com len(list(doc.sents))

In [20]:
import spacy

def contar_palavras_sentencas_spacy(df, coluna_texto="texto", modelo="pt_core_news_lg"):
    """
    Conta número de palavras e número de sentenças usando spaCy.
    Retorna o DataFrame original com duas novas colunas:
    - n_palavras_spacy
    - n_sentencas_spacy
    """
    
    nlp = spacy.load(modelo)
    
    palavras_list = []
    sentencas_list = []
    
    for texto in df[coluna_texto]:
        if pd.isna(texto):
            palavras_list.append(0)
            sentencas_list.append(0)
            continue
        
        doc = nlp(texto)
        
        #n_palavras = len([t for t in doc if t.is_alpha])  # contar só palavras
        #n_palavras = len([t for t in doc if t.is_space])  # Contar todos os tokens, exceto espaços
        n_palavras = len(list(doc))                       # Contar todos os tokens, até os espaços
        n_sentencas = len(list(doc.sents))
        
        palavras_list.append(n_palavras)
        sentencas_list.append(n_sentencas)
    
    df[f"{coluna_texto}_n_palavras_spacy"] = palavras_list
    df[f"{coluna_texto}_n_sentencas_spacy"] = sentencas_list
    
    return df

df_spacy1 = df.copy()
df_spacy1 = contar_palavras_sentencas_spacy(df_spacy1 , coluna_texto="t-1")
df_spacy1 = contar_palavras_sentencas_spacy(df_spacy1, coluna_texto="t")
df_spacy1 = contar_palavras_sentencas_spacy(df_spacy1, coluna_texto="t+2")

df_spacy1 = df_spacy1.drop(columns=['Nome','t-1','t','t+2'])
df_spacy1

,Id_Empresa,t-1_n_palavras_spacy,t-1_n_sentencas_spacy,t_n_palavras_spacy,t_n_sentencas_spacy,t+2_n_palavras_spacy,t+2_n_sentencas_spacy
0,1,5466,162,5272,133,5315,152
1,2,5567,180,5594,166,5593,184
2,3,5642,183,5555,165,5513,204
3,4,5639,162,5478,149,5564,171
4,5,5551,163,5675,175,5687,166
5,6,5543,190,5573,191,5648,207
6,8,5569,156,5589,154,5403,162
7,9,5571,167,5426,171,5453,176
8,10,5599,170,5552,167,5668,183
9,11,5378,168,5385,167,5374,166
10,12,5614,185,5599,178,5721,182
11,13,5475,174,5482,178,5446,182
12,14,5308,155,5621,169,5622,181
13,15,5433,184,5397,185,5392,187
14,16,5627,171,5590,173,5467,181
15,17,5569,167,5407,146,5611,167
16,18,6170,129,5866,168,5989,131
17,19,5569,189,5631,193,5611,192
18,20,5587,167,5567,173,5588,166
19,21,5776,174,5889,190,5700,173
20,22,5571,197,5488,176,5590,179
21,23,5547,190,5589,203,5686,174
22,24,5514,162,5537,159,5547,171
23,25,5810,212,5839,172,5781,182
24,26,5545,180,5559,179,5610,179
25,27,5768,136,5735,142,6151,136
26,28,5434,161,5562,155,5801,136
27,29,5679,176,5688,165,5832,161
28,30,5750,187,5650,172,5628,158
29,31,5460,188,5472,180,5478,146
30,32,5796,178,5621,155,5817,168
31,33,5359,167,5467,170,5746,171
32,34,5503,180,5498,180,5557,176
33,35,5532,154,5550,158,5709,150
34,36,5803,163,5546,172,5852,159
35,37,5928,189,5905,170,5569,163
36,38,5506,163,5543,165,5554,169
37,39,5587,180,5619,175,5560,176
38,40,5622,171,5692,178,5890,178
39,41,5521,158,5538,152,5504,158
40,42,5481,182,5500,182,5555,180
41,43,5555,159,5771,200,5564,141
42,44,5606,178,5439,164,5439,171
43,45,5441,155,5557,145,5435,157
44,46,5642,174,5616,190,5609,173
45,47,6025,167,6028,169,5682,171
46,48,5541,179,5544,180,5535,189
47,49,5527,195,5454,168,0,0
48,50,5551,167,5611,152,5545,162
49,51,5588,159,5745,140,5551,133

# Contagem de adjetivos e advérbios com NLTK
Este bloco vai além da contagem de palavras e sentenças. Ele tenta identificar classes gramaticais.

**O que acontece:**
- importa mac_morpho e os taggers do NLTK
- treina um tagger de sequência com o corpus mac_morpho

Isso significa que o notebook tenta "rotular" cada palavra com sua função gramatical, como:
- adjetivo
- advérbio

**Função criada:**
`contar_adj_adv_nltk(texto):`
- se o texto estiver vazio, retorna (0, 0)
- tokeniza o texto
- aplica o tagger
- conta quantas palavras foram etiquetadas como:
    - ADJ → adjetivo
    - ADV → advérbio

In [25]:
import nltk
from nltk.corpus import mac_morpho
from nltk.tag import UnigramTagger, BigramTagger

# Treinar um tagger para PT-BR com mac_morpho
tagged_sents = mac_morpho.tagged_sents()
uni_tagger = UnigramTagger(tagged_sents)
bi_tagger = BigramTagger(tagged_sents, backoff=uni_tagger)

def contar_adj_adv_nltk(texto):
    if pd.isna(texto) or not isinstance(texto, str):
        return 0, 0
    tokens = nltk.word_tokenize(texto, language="portuguese")
    tags = bi_tagger.tag(tokens)

    # etiquetas do mac_morpho:
    # ADJETIVO → "ADJ"
    # ADVÉRBIO → "ADV"
    adj = sum(1 for _, tag in tags if tag == "ADJ")
    adv = sum(1 for _, tag in tags if tag == "ADV")

    return adj, adv

df2 = df.copy()

# t-1
df2["adj_t_1"], df2["adv_t_1"] = zip(*df2["t-1"].apply(contar_adj_adv_nltk))

# t
df2["adj_t"], df2["adv_t"] = zip(*df2["t"].apply(contar_adj_adv_nltk))

# t+2
df2["adj_t2"], df2["adv_t2"] = zip(*df2["t+2"].apply(contar_adj_adv_nltk))

df2 = df2.drop(columns=['Nome','t-1','t','t+2'])
df2

    Id_Empresa  adj_t_1  adv_t_1  adj_t  adv_t  adj_t2  adv_t2
0            1      404      144    318    131     339     154
1            2      390      144    379    164     397     142
2            3      391      131    394    103     408     104
3            4      351      115    343    108     306     112
4            5      438      160    423    158     455     152
5            6      359      105    375    107     350     100
6            8      367      127    372    131     432     166
7            9      383      117    390    157     379     147
8           10      406      144    416    151     361     116
9           11      383      122    374    130     378     132
10          12      371      112    364    114     356     124
11          13      406      155    410    155     446     143
12          14      309      107    331    115     325     142
13          15      436      164    421    163     423     161
14          16      300      151    302    151     405     139
15          17      300      139    399    139     355     129
16          18      197       95    320    111     257     126
17          19      408      121    369    160     402     150
18          20      435      147    429    125     425     150
19          21      390      103    371    140     374     124
20          22      386      115    386    101     406     118
21          23      395      158    410    147     440     121
22          24      419      140    412    132     413     144
23          25      360      129    315    120     312     121
24          26      306      141    320    141     331     137
25          27      329      115    345    126     302     108
26          28      364      139    315    130     227     122
27          29      337      108    384    115     357     123
28          30      378      115    415    123     384     132
29          31      395      147    387    145     407     147
30          32      282      113    386    132     221      91
31          33      396      157    403    156     379     123
32          34      447      128    459    126     442     121
33          35      430      149    410    145     360     139
34          36      431      150    418    142     406     136
35          37      431      129    420    127     411     147
36          38      451      134    456    141     436     130
37          39      402      126    395    123     410     127
38          40      339      132    333    128     338     137
39          41      448      140    455    133     415     146
40          42      387      122    362    120     349     118
41          43      385      114    356    107     408     154
42          44      373      116    479    142     467     137
43          45      362      148    329    121     388     132
44          46      349      144    345    140     338     126
45          47      269       77    253     81     351      99
46          48      408      175    412    177     409     190
47          49      451      149    459    161       0       0
48          50      328      131    350    138     360     132
49          51      411      133    342    125     404     127

# Contagem de adjetivos e advérbios com spaCy
Este é o último bloco e é muito similar ao anterior, mas usando spaCy.

**O que acontece:**
- carrega novamente o modelo `pt_core_news_lg`
- define `contar_adj_adv_spacy(texto)`

**Como ele funciona:**
Para cada texto:
- cria um objeto `Doc`
- verifica cada token com token.pos_
- conta os tokens cujo rótulo é:
    - "ADJ" para adjetivo
    - "ADV" para advérbio

In [28]:
import spacy
import pandas as pd

nlp = spacy.load("pt_core_news_lg")

def contar_adj_adv_spacy(texto):
    if pd.isna(texto) or not isinstance(texto, str):
        return 0, 0
    
    doc = nlp(texto)

    adj = sum(1 for token in doc if token.pos_ == "ADJ")
    adv = sum(1 for token in doc if token.pos_ == "ADV")

    return adj, adv

df2 = df.copy()

# t-1
df2["adj_t_1"], df2["adv_t_1"] = zip(*df2["t-1"].apply(contar_adj_adv_spacy))

# t
df2["adj_t"], df2["adv_t"] = zip(*df2["t"].apply(contar_adj_adv_spacy))

# t+2
df2["adj_t2"], df2["adv_t2"] = zip(*df2["t+2"].apply(contar_adj_adv_spacy))

df2 = df2.drop(columns=['Nome','t-1','t','t+2'])
df2

    Id_Empresa  adj_t_1  adv_t_1  adj_t  adv_t  adj_t2  adv_t2
0            1      468      148    358    164     380     166
1            2      450      139    450    164     460     143
2            3      445      130    438    113     452     106
3            4      384      113    387    108     354     114
4            5      478      151    454    151     480     154
5            6      399       79    403     84     395      77
6            8      433      128    427    130     488     154
7            9      404      101    424    152     415     147
8           10      478      133    486    141     427     108
9           11      457      138    451    140     457     141
10          12      418       81    418     88     413     120
11          13      465      163    470    159     510     142
12          14      386       91    416     96     413     121
13          15      492      168    479    165     479     163
14          16      414      162    389    164     439     145
15          17      353      136    453    147     392     107
16          18      246       97    374    114     300     108
17          19      441      114    406    160     439     159
18          20      503      117    484    103     488     123
19          21      440      105    394    164     426     123
20          22      458      138    451    135     468     146
21          23      439      157    455    150     455     138
22          24      474      127    465    124     470     129
23          25      403      149    371    116     359     119
24          26      347      117    371    114     385     113
25          27      384      115    393    121     349      92
26          28      402      134    367    125     261     122
27          29      400      101    426    108     397     115
28          30      420      105    464    104     439     109
29          31      445      152    432    159     461     158
30          32      353      102    441    109     276     103
31          33      449      149    452    142     424     129
32          34      519      127    512    136     510     136
33          35      495      132    476    125     428     138
34          36      494      166    482    161     448     159
35          37      493      128    483    126     475     126
36          38      502      137    508    141     502     142
37          39      443      131    434    124     446     133
38          40      372      133    387    112     390     121
39          41      507      150    511    134     486     130
40          42      446      115    429    113     411     117
41          43      427      130    406    100     468     169
42          44      398      118    540    131     525     122
43          45      462      139    410    111     471     130
44          46      415      132    396    127     419     115
45          47      308       42    285     44     390     114
46          48      482      180    479    183     471     196
47          49      525      142    533    147       0       0
48          50      362      118    380    137     409     127
49          51      503      127    395    148     485     123